export const videos = [
  {
    title: "Chanting for Victory! ANFASSC Motivates Our Players from the Stand",
    category: "MATCH HIGHLIGHTS",
    date: "17 JUL 25",
    duration: "3:45",
    video: "https://www.youtube.com/embed/v7QCUd0llMA",
    thumbnail: "https://img.youtube.com/vi/v7QCUd0llMA/hqdefault.jpg",
  },
  {
    title: "Training Session: Team Preparation for Euro Semi-Final",
    category: "TRAINING",
    date: "16 JUL 25",
    duration: "2:30",
    video: "https://www.youtube.com/embed/uGXqT-QkyNY",
    thumbnail: "https://img.youtube.com/vi/uGXqT-QkyNY/hqdefault.jpg",
  },
  {
    title: "ANFASSC in action during the Round of 16 match against Cameroon..",
    category: "INTERVIEWS",
    date: "15 JUL 25",
    duration: "4:12",
    video: "https://www.youtube.com/embed/JW0esa3_JqI",
    thumbnail: "https://img.youtube.com/vi/JW0esa3_JqI/hqdefault.jpg",
  },
  {
    title: "ANFASSC in Action: Unleashing the Power of Sport Passion",
    category: "BEHIND THE SCENES",
    date: "14 JUL 25",
    duration: "5:20",
    video: "https://www.youtube.com/embed/z3pqizReJwI",
    thumbnail: "https://img.youtube.com/vi/z3pqizReJwI/hqdefault.jpg",
  },
  {
    title: "ANFASSC welcome junior female footballers",
    category: "ACADEMY",
    date: "13 JUL 25",
    duration: "3:15",
    video: "https://www.youtube.com/embed/yubJ6t6tgew",
    thumbnail: "https://img.youtube.com/vi/yubJ6t6tgew/hqdefault.jpg",
  },
  {
    title: "ANFASSC President: Prince Abayomi Ogunjimi Drums Support",
    category: "ACADEMY",
    date: "13 JUL 25",
    duration: "3:15",
    video: "https://youtube.com/embed/f8gMSzhaO2w",
    thumbnail: "https://img.youtube.com/vi/f8gMSzhaO2w/hqdefault.jpg",
  },
  {
    title: "ANFASSC IN GLANCE: OUR MEMORIES",
    category: "ACADEMY",
    date: "13 JUL 25",
    duration: "3:15",
    video: "https://youtube.com/embed/9Q3s5Axmmy8",
    thumbnail: "https://img.youtube.com/vi/9Q3s5Axmmy8/hqdefault.jpg",
  },
  {
    title: "ANFASSC: Happiness Depends on Ourselves",
    category: "ACADEMY",
    date: "13 JUL 25",
    duration: "3:15",
    video: "https://youtube.com/embed/IZjHNB2h39Y",
    thumbnail: "https://img.youtube.com/vi/IZjHNB2h39Y/hqdefault.jpg",
  },
  {
    title: "ANFCON 2023: ANFASSC Supporting Super Eagles",
    category: "ACADEMY",
    date: "13 JUL 25",
    duration: "3:15",
    video: "https://youtube.com/embed/0Gy_s775U-s",
    thumbnail: "https://img.youtube.com/vi/0Gy_s775U-s/hqdefault.jpg",
  },
  {
    title: "Memories from our road trip to Cameroon at the last Nations' Cup",
    category: "ACADEMY",
    date: "13 JUL 25",
    duration: "3:15",
    video: "https://youtube.com/embed/jk2ulxvVwGk",
    thumbnail: "https://img.youtube.com/vi/jk2ulxvVwGk/hqdefault.jpg",
  },
  {
    title: "Authentic, doing what they know best",
    category: "ACADEMY",
    date: "13 JUL 25",
    duration: "3:15",
    video: "https://youtube.com/embed/9tmHbA51p1M",
    thumbnail: "https://img.youtube.com/vi/9tmHbA51p1M/hqdefault.jpg",
  },
  {
    title: "More Than Cheers: The Legacy and Identity of ANFASSC",
    category: "ACADEMY",
    date: "13 JUL 25",
    duration: "3:15",
    video: "https://youtube.com/embed/Lvoa7LlR0FE",
    thumbnail: "https://img.youtube.com/vi/Lvoa7LlR0FE/hqdefault.jpg",
  },
]